from typing import Optional
import numpy as np
import pandas as pd
import QuantLib as ql
# in-house
from fixedincomelib.date.basics import (Date, Period)


def add_period(
    start_date : Date,
    term : Period,
    business_day_convention : int,
    holiday_convention : ql.Calendar,
    end_of_month : Optional[bool]=False) -> Date:

    # a zero-length term is a pure business-day adjustment -- Calendar.advance(date, 0D, conv) and
    # Calendar.adjust(date, conv) give identical results (verified against weekend/holiday cases),
    # and adjust() skips the per-unit (Days/Weeks/Months/Years) branching advance() does for a
    # general period. Zero-length terms are common throughout the codebase (TermOrDate("0D")
    # payment/lookback/cutoff defaults), so this is a broadly-applicable fast path, not specific
    # to any one caller.
    if term.length() == 0:
        return move_to_business_day(start_date, business_day_convention, holiday_convention)
    return Date(holiday_convention.advance(start_date, term, business_day_convention, end_of_month))

def subtract_period(
    start_date : Date,
    term : Period,
    business_day_convention : int,
    holiday_convention : ql.Calendar,
    end_of_month : Optional[bool]=False) -> Date:

    return add_period(
        start_date, Period.negate_period(term), business_day_convention, holiday_convention, end_of_month
    )

def move_to_business_day(
    input_date: Date,
    business_day_convention: int,
    holiday_convention: ql.Calendar) -> Date:

    return Date(holiday_convention.adjust(input_date, business_day_convention))

def accrued(
    start_date: Date,
    end_date: Date,
    accrual_basis: Optional[ql.DayCounter] = ql.ActualActual(ql.ActualActual.ISDA),
    business_day_convention: Optional[int] = ql.Preceding,
    holiday_convention: Optional[ql.Calendar] = ql.NullCalendar(),
    end_date_is_business_day: Optional[bool] = False) -> float:

    # skip the business-day adjustment when the caller already knows end_date is one -- e.g. a
    # date freshly generated by daily_business_day_dates/ql.Schedule, where re-adjusting is
    # guaranteed to be a no-op but still pays for a Calendar round trip. Defaults to False (today's
    # behavior: always adjust), so every existing caller is unaffected.
    adjusted_end_dt = (
        end_date
        if end_date_is_business_day
        else move_to_business_day(end_date, business_day_convention, holiday_convention)
    )
    return accrual_basis.yearFraction(start_date, adjusted_end_dt)

def is_business_day(input_date: Date, holiday_convention: ql.Calendar) -> bool:
    return holiday_convention.isBusinessDay(input_date)

def is_holiday(input_date: Date, holiday_convention: ql.Calendar) -> bool:
    return holiday_convention.isHoliday(input_date)

def is_end_of_month(input_date: Date, holiday_convention: ql.Calendar) -> bool:
    return holiday_convention.isEndOfMonth(input_date)

def end_of_month(input_date: Date, holiday_convention: ql.Calendar) -> Date:
    return holiday_convention.endOfMonth(input_date)

def make_schedule(
    start_date: Date,
    end_date: Date,
    accrual_period: Period,
    holiday_convention: ql.Calendar,
    business_day_convention: int,
    accrual_basis: ql.DayCounter,
    rule: Optional[int] = ql.DateGeneration.Backward,
    end_of_month: Optional[bool] = False,
    fix_in_arrear: Optional[bool] = False,
    fixing_offset: Optional[Period] = Period(ql.NoFrequency),
    payment_offset: Optional[Period] = Period(ql.NoFrequency),
    payment_business_day_convention: Optional[int] = ql.Following,
    payment_holiday_convention: Optional[ql.Calendar] = ql.NullCalendar(),
    first_regular_date : Optional[Date]=Date(),
    next_to_last_date : Optional[Date]=Date()) -> pd.DataFrame:

    assert rule in [ql.DateGeneration.Forward, ql.DateGeneration.Backward]
    
    # set up start date and end date of each period
    this_schedule = ql.Schedule(
        start_date,
        end_date,
        accrual_period,
        holiday_convention,
        business_day_convention,
        business_day_convention,
        rule,
        end_of_month,
        first_regular_date,
        next_to_last_date)

    # add fixing date and payment date
    start_dates = this_schedule.dates()[:-1]
    end_dates = this_schedule.dates()[1:]
    fixing_dates, payment_dates, accs = [], [], []
    for s, e in zip(start_dates, end_dates):
        f = s
        if fixing_offset.is_valid():
            f = add_period(
                e if fix_in_arrear else s, 
                fixing_offset, 
                business_day_convention, 
                holiday_convention)
        fixing_dates.append(f)
        p = e
        
        if payment_offset.is_valid():
            p = add_period(
                e, 
                payment_offset, 
                payment_business_day_convention, 
                payment_holiday_convention)
        else:
            p = move_to_business_day(
                e,
                payment_business_day_convention,
                payment_holiday_convention
            )
        payment_dates.append(p)
        accs.append(accrued(s, e, accrual_basis, business_day_convention, holiday_convention))

    # set up container
    df = pd.DataFrame(columns=["StartDate", "EndDate", "FixingDate", "PaymentDate", "Accrued"])
    df["StartDate"] = start_dates
    df["EndDate"] = end_dates
    df["FixingDate"] = fixing_dates
    df["PaymentDate"] = payment_dates
    df["Accrued"] = accs

    return df

def daily_business_day_dates(
    start_date: Date,
    end_date: Date,
    business_day_convention: int,
    holiday_convention: ql.Calendar) -> list:

    # businessDayList is one linear C++ call. ql.Schedule with a 1-day tenor resolves each date as
    # start + n days, so it is quadratic in the span -- 2.8us/date over a ~65-day accrual period but
    # 30.9us/date over 60Y -- and it throws "degenerate single date schedule" when both endpoints
    # adjust onto the same business day. Adjusting the endpoints here reproduces the terminationDate
    # roll the Schedule applied: without it an end date on a holiday would stop short of the next
    # fixing instead of rolling forward onto it, silently dropping the period's last accrual day.
    return list(
        holiday_convention.businessDayList(
            holiday_convention.adjust(start_date, business_day_convention),
            holiday_convention.adjust(end_date, business_day_convention),
        )
    )

def frequency_from_period(p: Period) -> float:
    freq = p.frequency()
    return float(freq)
